begin;

-- Generated by scripts/import-transit-data.mjs

insert into public.transit_places (slug, name, aliases, lat, lng, zone, corridor, source, metadata)
values ('gate-5-karangalan', 'Gate 5 Karangalan', ARRAY['Karangalan', 'Gate 5', 'Karangalan Gate 5']::text[], 14.6148, 121.1018, 'pasig', 'ortigas-avenue', 'community', '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  lat = excluded.lat,
  lng = excluded.lng,
  zone = excluded.zone,
  corridor = excluded.corridor,
  source = excluded.source,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.transit_places (slug, name, aliases, lat, lng, zone, corridor, source, metadata)
values ('sta-lucia-east-grand-mall', 'Sta. Lucia East Grand Mall', ARRAY['Sta Lucia', 'Sta. Lucia']::text[], 14.6191, 121.1017, 'marikina', 'marcos-highway', 'community', '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  lat = excluded.lat,
  lng = excluded.lng,
  zone = excluded.zone,
  corridor = excluded.corridor,
  source = excluded.source,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.transit_places (slug, name, aliases, lat, lng, zone, corridor, source, metadata)
values ('ligaya', 'Ligaya', ARRAY['Ligaya Marikina']::text[], 14.6265, 121.0916, 'marikina', 'marcos-highway', 'community', '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  lat = excluded.lat,
  lng = excluded.lng,
  zone = excluded.zone,
  corridor = excluded.corridor,
  source = excluded.source,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.transit_places (slug, name, aliases, lat, lng, zone, corridor, source, metadata)
values ('santolan-pasig', 'Santolan Pasig', ARRAY['Santolan', 'Santolan Area']::text[], 14.6134, 121.0907, 'pasig', 'marcos-highway', 'community', '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  lat = excluded.lat,
  lng = excluded.lng,
  zone = excluded.zone,
  corridor = excluded.corridor,
  source = excluded.source,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.transit_places (slug, name, aliases, lat, lng, zone, corridor, source, metadata)
values ('rosario-pasig', 'Rosario Pasig', ARRAY['Rosario']::text[], 14.5885, 121.0837, 'pasig', 'ortigas-avenue', 'community', '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  lat = excluded.lat,
  lng = excluded.lng,
  zone = excluded.zone,
  corridor = excluded.corridor,
  source = excluded.source,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.transit_places (slug, name, aliases, lat, lng, zone, corridor, source, metadata)
values ('eastwood-city', 'Eastwood City', ARRAY[]::text[], 14.6108, 121.08, 'pasig', 'c5', 'community', '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  lat = excluded.lat,
  lng = excluded.lng,
  zone = excluded.zone,
  corridor = excluded.corridor,
  source = excluded.source,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.transit_places (slug, name, aliases, lat, lng, zone, corridor, source, metadata)
values ('manggahan-pasig', 'Manggahan Pasig', ARRAY['Manggahan']::text[], 14.6052, 121.0932, 'pasig', 'ortigas-avenue', 'community', '{}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  lat = excluded.lat,
  lng = excluded.lng,
  zone = excluded.zone,
  corridor = excluded.corridor,
  source = excluded.source,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'gate-5-karangalan_to_sta-lucia-east-grand-mall',
  'gate-5-karangalan',
  'sta-lucia-east-grand-mall',
  'Walk + jeepney to Sta. Lucia',
  'community',
  'community-sourced',
  'local-test',
  'User-tested route: cross to Felix Ave East Service Road, then ride a jeep signed Sta. Lucia, Cubao, or Tropical.',
  14,
  13,
  2680
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'gate-5-karangalan_to_sta-lucia-east-grand-mall');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'walk', 'Gate 5 Karangalan', 'Felix Ave East Service Road', 'Cross to Felix Ave East Service Road', null, 4, 280, 0, false, '{}'::jsonb
from public.community_routes
where slug = 'gate-5-karangalan_to_sta-lucia-east-grand-mall'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 2, 'jeepney', 'Felix Ave East Service Road', 'Sta. Lucia East Grand Mall', 'Ride a jeepney signed Sta. Lucia, Cubao, or Tropical and get off at Sta. Lucia', 'Sta. Lucia / Cubao / Tropical jeep', 10, 2400, 13, false, '{}'::jsonb
from public.community_routes
where slug = 'gate-5-karangalan_to_sta-lucia-east-grand-mall'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'sta-lucia-east-grand-mall_to_gate-5-karangalan',
  'sta-lucia-east-grand-mall',
  'gate-5-karangalan',
  'Jeepney + walk to Gate 5 Karangalan',
  'community',
  'community-sourced',
  'local-test',
  'Reverse of the user-tested Sta. Lucia route.',
  15,
  13,
  2680
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'sta-lucia-east-grand-mall_to_gate-5-karangalan');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Sta. Lucia East Grand Mall', 'Felix Ave loading area', 'Ride a jeepney signed Karangalan or Gate 5 and get off near Felix Ave', 'Karangalan / Gate 5 jeep', 11, 2400, 13, false, '{}'::jsonb
from public.community_routes
where slug = 'sta-lucia-east-grand-mall_to_gate-5-karangalan'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 2, 'walk', 'Felix Ave loading area', 'Gate 5 Karangalan', 'Walk into Gate 5 Karangalan', null, 4, 280, 0, false, '{}'::jsonb
from public.community_routes
where slug = 'sta-lucia-east-grand-mall_to_gate-5-karangalan'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'sta-lucia-east-grand-mall_to_ligaya',
  'sta-lucia-east-grand-mall',
  'ligaya',
  'Jeepney to Ligaya',
  'community',
  'community-sourced',
  'starter-network',
  'Starter community segment along the Marcos Highway corridor.',
  9,
  13,
  1700
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'sta-lucia-east-grand-mall_to_ligaya');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Sta. Lucia East Grand Mall', 'Ligaya', 'Ride a jeepney toward Ligaya and get off at Ligaya', 'Ligaya jeep', 9, 1700, 13, false, '{}'::jsonb
from public.community_routes
where slug = 'sta-lucia-east-grand-mall_to_ligaya'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'ligaya_to_sta-lucia-east-grand-mall',
  'ligaya',
  'sta-lucia-east-grand-mall',
  'Jeepney to Sta. Lucia',
  'community',
  'community-sourced',
  'starter-network',
  'Starter community segment along the Marcos Highway corridor.',
  9,
  13,
  1700
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'ligaya_to_sta-lucia-east-grand-mall');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Ligaya', 'Sta. Lucia East Grand Mall', 'Ride a jeepney toward Sta. Lucia and get off at Sta. Lucia', 'Sta. Lucia jeep', 9, 1700, 13, false, '{}'::jsonb
from public.community_routes
where slug = 'ligaya_to_sta-lucia-east-grand-mall'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'ligaya_to_rosario-pasig',
  'ligaya',
  'rosario-pasig',
  'Jeepney via Ligaya - Rosario',
  'community',
  'community-sourced',
  'starter-network',
  'Starter cross-corridor segment between Marikina and Pasig hubs.',
  20,
  22,
  6100
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'ligaya_to_rosario-pasig');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Ligaya', 'Rosario Pasig', 'Ride a jeepney through the Ligaya - Rosario corridor and get off at Rosario', 'Ligaya - Rosario jeep', 20, 6100, 22, false, '{}'::jsonb
from public.community_routes
where slug = 'ligaya_to_rosario-pasig'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'ligaya_to_santolan-pasig',
  'ligaya',
  'santolan-pasig',
  'Jeepney to Santolan Pasig',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for the Ligaya - Santolan Pasig corridor.',
  11,
  13,
  2800
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'ligaya_to_santolan-pasig');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Ligaya', 'Santolan Pasig', 'Ride a jeepney toward Santolan Pasig and get off in the Santolan area', 'Ligaya - Santolan jeep', 11, 2800, 13, false, '{}'::jsonb
from public.community_routes
where slug = 'ligaya_to_santolan-pasig'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'santolan-pasig_to_ligaya',
  'santolan-pasig',
  'ligaya',
  'Jeepney to Ligaya',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for the Santolan Pasig - Ligaya corridor.',
  11,
  13,
  2800
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'santolan-pasig_to_ligaya');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Santolan Pasig', 'Ligaya', 'Ride a jeepney toward Ligaya and get off at Ligaya', 'Santolan - Ligaya jeep', 11, 2800, 13, false, '{}'::jsonb
from public.community_routes
where slug = 'santolan-pasig_to_ligaya'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'rosario-pasig_to_ligaya',
  'rosario-pasig',
  'ligaya',
  'Jeepney via Rosario - Ligaya',
  'community',
  'community-sourced',
  'starter-network',
  'Starter cross-corridor segment between Pasig and Marikina hubs.',
  20,
  22,
  6100
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'rosario-pasig_to_ligaya');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Rosario Pasig', 'Ligaya', 'Ride a jeepney through the Rosario - Ligaya corridor and get off at Ligaya', 'Rosario - Ligaya jeep', 20, 6100, 22, false, '{}'::jsonb
from public.community_routes
where slug = 'rosario-pasig_to_ligaya'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'santolan-pasig_to_rosario-pasig',
  'santolan-pasig',
  'rosario-pasig',
  'Jeepney to Rosario',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for the Santolan Pasig - Rosario corridor.',
  17,
  15,
  4700
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'santolan-pasig_to_rosario-pasig');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Santolan Pasig', 'Rosario Pasig', 'Ride a jeepney toward Rosario and get off at Rosario Pasig', 'Santolan - Rosario jeep', 17, 4700, 15, false, '{}'::jsonb
from public.community_routes
where slug = 'santolan-pasig_to_rosario-pasig'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'rosario-pasig_to_santolan-pasig',
  'rosario-pasig',
  'santolan-pasig',
  'Jeepney to Santolan Pasig',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for the Rosario - Santolan Pasig corridor.',
  17,
  15,
  4700
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'rosario-pasig_to_santolan-pasig');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Rosario Pasig', 'Santolan Pasig', 'Ride a jeepney toward Santolan Pasig and get off in the Santolan area', 'Rosario - Santolan jeep', 17, 4700, 15, false, '{}'::jsonb
from public.community_routes
where slug = 'rosario-pasig_to_santolan-pasig'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'rosario-pasig_to_eastwood-city',
  'rosario-pasig',
  'eastwood-city',
  'Jeepney to Eastwood',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for the Rosario - Eastwood corridor.',
  16,
  15,
  4500
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'rosario-pasig_to_eastwood-city');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Rosario Pasig', 'Eastwood City', 'Ride a jeepney toward Eastwood and get off near Eastwood City', 'Rosario - Eastwood jeep', 16, 4500, 15, false, '{}'::jsonb
from public.community_routes
where slug = 'rosario-pasig_to_eastwood-city'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'eastwood-city_to_rosario-pasig',
  'eastwood-city',
  'rosario-pasig',
  'Jeepney to Rosario',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for the Eastwood - Rosario corridor.',
  16,
  15,
  4500
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'eastwood-city_to_rosario-pasig');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Eastwood City', 'Rosario Pasig', 'Ride a jeepney toward Rosario and get off at Rosario Pasig', 'Eastwood - Rosario jeep', 16, 4500, 15, false, '{}'::jsonb
from public.community_routes
where slug = 'eastwood-city_to_rosario-pasig'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'rosario-pasig_to_manggahan-pasig',
  'rosario-pasig',
  'manggahan-pasig',
  'Jeepney to Manggahan',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for eastern Pasig coverage.',
  12,
  15,
  3600
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'rosario-pasig_to_manggahan-pasig');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Rosario Pasig', 'Manggahan Pasig', 'Ride a jeepney toward Manggahan and get off at Manggahan Pasig', 'Rosario - Manggahan jeep', 12, 3600, 15, false, '{}'::jsonb
from public.community_routes
where slug = 'rosario-pasig_to_manggahan-pasig'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

insert into public.community_routes (
  slug, origin_slug, destination_slug, summary, source, confidence, source_url, notes, total_duration, total_cost, total_distance_meters
)
values (
  'manggahan-pasig_to_rosario-pasig',
  'manggahan-pasig',
  'rosario-pasig',
  'Jeepney to Rosario',
  'community',
  'community-sourced',
  'starter-network',
  'Starter segment for eastern Pasig coverage.',
  12,
  15,
  3600
)
on conflict (slug) do update set
  origin_slug = excluded.origin_slug,
  destination_slug = excluded.destination_slug,
  summary = excluded.summary,
  source = excluded.source,
  confidence = excluded.confidence,
  source_url = excluded.source_url,
  notes = excluded.notes,
  total_duration = excluded.total_duration,
  total_cost = excluded.total_cost,
  total_distance_meters = excluded.total_distance_meters,
  updated_at = now();
delete from public.community_route_steps
where route_id in (select id from public.community_routes where slug = 'manggahan-pasig_to_rosario-pasig');
insert into public.community_route_steps (
  route_id, step_order, mode, from_label, to_label, instruction, line_name, duration_minutes, distance_meters, cost, is_estimated, metadata
)
select id, 1, 'jeepney', 'Manggahan Pasig', 'Rosario Pasig', 'Ride a jeepney toward Rosario and get off at Rosario Pasig', 'Manggahan - Rosario jeep', 12, 3600, 15, false, '{}'::jsonb
from public.community_routes
where slug = 'manggahan-pasig_to_rosario-pasig'
on conflict (route_id, step_order) do update set
  mode = excluded.mode,
  from_label = excluded.from_label,
  to_label = excluded.to_label,
  instruction = excluded.instruction,
  line_name = excluded.line_name,
  duration_minutes = excluded.duration_minutes,
  distance_meters = excluded.distance_meters,
  cost = excluded.cost,
  is_estimated = excluded.is_estimated,
  metadata = excluded.metadata;

commit;
