begin;

-- Generated by scripts/import-transit-data.mjs

-- gtfs_agency from agency.txt

insert into public.gtfs_agency (
  agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone, agency_fare_url, agency_email, raw
)
values (
  'LRTA',
  'Manila Light Rail Transit Authority',
  'http://www.lrta.gov.ph/',
  'Asia/Manila',
  '',
  '',
  null,
  null,
  '{"agency_id":"LRTA","agency_name":"Manila Light Rail Transit Authority","agency_url":"http://www.lrta.gov.ph/","agency_timezone":"Asia/Manila","agency_lang":"","agency_phone":""}'::jsonb
)
on conflict (agency_id) do update set
  agency_name = excluded.agency_name,
  agency_url = excluded.agency_url,
  agency_timezone = excluded.agency_timezone,
  agency_lang = excluded.agency_lang,
  agency_phone = excluded.agency_phone,
  agency_fare_url = excluded.agency_fare_url,
  agency_email = excluded.agency_email,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_agency (
  agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone, agency_fare_url, agency_email, raw
)
values (
  'LTFRB',
  'LTFRB',
  'http://www.ltfrb.gov.ph/',
  'Asia/Manila',
  '',
  '',
  null,
  null,
  '{"agency_id":"LTFRB","agency_name":"LTFRB","agency_url":"http://www.ltfrb.gov.ph/","agency_timezone":"Asia/Manila","agency_lang":"","agency_phone":""}'::jsonb
)
on conflict (agency_id) do update set
  agency_name = excluded.agency_name,
  agency_url = excluded.agency_url,
  agency_timezone = excluded.agency_timezone,
  agency_lang = excluded.agency_lang,
  agency_phone = excluded.agency_phone,
  agency_fare_url = excluded.agency_fare_url,
  agency_email = excluded.agency_email,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_agency (
  agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone, agency_fare_url, agency_email, raw
)
values (
  'MRTC',
  'Manila Metro Rail Transit Corporation',
  'http://dotcmrt3.gov.ph',
  'Asia/Manila',
  '',
  '',
  null,
  null,
  '{"agency_id":"MRTC","agency_name":"Manila Metro Rail Transit Corporation","agency_url":"http://dotcmrt3.gov.ph","agency_timezone":"Asia/Manila","agency_lang":"","agency_phone":""}'::jsonb
)
on conflict (agency_id) do update set
  agency_name = excluded.agency_name,
  agency_url = excluded.agency_url,
  agency_timezone = excluded.agency_timezone,
  agency_lang = excluded.agency_lang,
  agency_phone = excluded.agency_phone,
  agency_fare_url = excluded.agency_fare_url,
  agency_email = excluded.agency_email,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_agency (
  agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone, agency_fare_url, agency_email, raw
)
values (
  'Maritime Industry Authority',
  'MARINA',
  'http://www.marina.gov.ph',
  'Asia/Manila',
  '',
  '',
  null,
  null,
  '{"agency_id":"Maritime Industry Authority","agency_name":"MARINA","agency_url":"http://www.marina.gov.ph","agency_timezone":"Asia/Manila","agency_lang":"","agency_phone":""}'::jsonb
)
on conflict (agency_id) do update set
  agency_name = excluded.agency_name,
  agency_url = excluded.agency_url,
  agency_timezone = excluded.agency_timezone,
  agency_lang = excluded.agency_lang,
  agency_phone = excluded.agency_phone,
  agency_fare_url = excluded.agency_fare_url,
  agency_email = excluded.agency_email,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_agency (
  agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone, agency_fare_url, agency_email, raw
)
values (
  'PNR',
  'Philippine National Railways',
  'http://www.pnr.gov.ph/',
  'Asia/Manila',
  '',
  '',
  null,
  null,
  '{"agency_id":"PNR","agency_name":"Philippine National Railways","agency_url":"http://www.pnr.gov.ph/","agency_timezone":"Asia/Manila","agency_lang":"","agency_phone":""}'::jsonb
)
on conflict (agency_id) do update set
  agency_name = excluded.agency_name,
  agency_url = excluded.agency_url,
  agency_timezone = excluded.agency_timezone,
  agency_lang = excluded.agency_lang,
  agency_phone = excluded.agency_phone,
  agency_fare_url = excluded.agency_fare_url,
  agency_email = excluded.agency_email,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_agency (
  agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone, agency_fare_url, agency_email, raw
)
values (
  'FORT',
  'The Fort Bus',
  'http://bgcbus.com/',
  'Asia/Manila',
  '',
  '',
  null,
  null,
  '{"agency_id":"FORT","agency_name":"The Fort Bus","agency_url":"http://bgcbus.com/","agency_timezone":"Asia/Manila","agency_lang":"","agency_phone":""}'::jsonb
)
on conflict (agency_id) do update set
  agency_name = excluded.agency_name,
  agency_url = excluded.agency_url,
  agency_timezone = excluded.agency_timezone,
  agency_lang = excluded.agency_lang,
  agency_phone = excluded.agency_phone,
  agency_fare_url = excluded.agency_fare_url,
  agency_email = excluded.agency_email,
  raw = excluded.raw,
  imported_at = now();

commit;
