begin;

-- Generated by scripts/import-transit-data.mjs

-- gtfs_calendar from calendar.txt

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881614',
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  '20130617',
  '20200630',
  '{"service_id":"881614","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"0","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '880893',
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  '20130617',
  '20200630',
  '{"service_id":"880893","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"1","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881744',
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  '20130617',
  '20200630',
  '{"service_id":"881744","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"0","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '882006',
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  '20130617',
  '20200630',
  '{"service_id":"882006","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"0","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '882002',
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  '20130617',
  '20200630',
  '{"service_id":"882002","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"1","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '880772',
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  '20130617',
  '20200630',
  '{"service_id":"880772","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"0","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '880774',
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  '20130617',
  '20200630',
  '{"service_id":"880774","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"1","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881444',
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  '20130617',
  '20200630',
  '{"service_id":"881444","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"0","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881445',
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  '20130617',
  '20200630',
  '{"service_id":"881445","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"0","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881397',
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  '20130617',
  '20200630',
  '{"service_id":"881397","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"1","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881408',
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  '20130617',
  '20200630',
  '{"service_id":"881408","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"0","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881411',
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  '20130617',
  '20200630',
  '{"service_id":"881411","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"0","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '880851',
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  '20130617',
  '20200630',
  '{"service_id":"880851","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"0","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '880853',
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  '20130617',
  '20200630',
  '{"service_id":"880853","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"1","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881502',
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  '20130617',
  '20200630',
  '{"service_id":"881502","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"0","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881578',
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  '20130617',
  '20200630',
  '{"service_id":"881578","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"1","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '724594',
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  '20130617',
  '20200630',
  '{"service_id":"724594","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"1","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  '881579',
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  '20130617',
  '20200630',
  '{"service_id":"881579","monday":"0","tuesday":"0","wednesday":"0","thursday":"0","friday":"0","saturday":"1","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  'WEEKDAYS',
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  '20130617',
  '20200630',
  '{"service_id":"WEEKDAYS","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"0","sunday":"0","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_calendar (
  service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date, raw
)
values (
  'DAILY',
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  '20130617',
  '20200630',
  '{"service_id":"DAILY","monday":"1","tuesday":"1","wednesday":"1","thursday":"1","friday":"1","saturday":"1","sunday":"1","start_date":"20130617","end_date":"20200630"}'::jsonb
)
on conflict (service_id) do update set
  monday = excluded.monday,
  tuesday = excluded.tuesday,
  wednesday = excluded.wednesday,
  thursday = excluded.thursday,
  friday = excluded.friday,
  saturday = excluded.saturday,
  sunday = excluded.sunday,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  raw = excluded.raw,
  imported_at = now();

commit;
