begin;

-- Generated by scripts/import-transit-data.mjs

-- gtfs_shapes from shapes.txt

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.365520000000002,
  121.05320000000002,
  80,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"80","shape_dist_traveled":"","shape_pt_lat":"14.365520000000002","shape_pt_lon":"121.05320000000002"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.365240000000002,
  121.05334000000002,
  81,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"81","shape_dist_traveled":"","shape_pt_lat":"14.365240000000002","shape_pt_lon":"121.05334000000002"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.364960000000002,
  121.05359000000001,
  82,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"82","shape_dist_traveled":"","shape_pt_lat":"14.364960000000002","shape_pt_lon":"121.05359000000001"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.364570000000002,
  121.05380000000001,
  83,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"83","shape_dist_traveled":"","shape_pt_lat":"14.364570000000002","shape_pt_lon":"121.05380000000001"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.359980000000002,
  121.05623000000001,
  84,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"84","shape_dist_traveled":"","shape_pt_lat":"14.359980000000002","shape_pt_lon":"121.05623000000001"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.355700000000002,
  121.05857000000002,
  85,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"85","shape_dist_traveled":"","shape_pt_lat":"14.355700000000002","shape_pt_lon":"121.05857000000002"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.348780000000003,
  121.06237000000002,
  86,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"86","shape_dist_traveled":"","shape_pt_lat":"14.348780000000003","shape_pt_lon":"121.06237000000002"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.347820000000004,
  121.06291000000002,
  87,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"87","shape_dist_traveled":"","shape_pt_lat":"14.347820000000004","shape_pt_lon":"121.06291000000002"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.346870000000004,
  121.06353000000001,
  88,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"88","shape_dist_traveled":"","shape_pt_lat":"14.346870000000004","shape_pt_lon":"121.06353000000001"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.338830000000005,
  121.07266000000001,
  89,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"89","shape_dist_traveled":"","shape_pt_lat":"14.338830000000005","shape_pt_lon":"121.07266000000001"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.334860000000004,
  121.07716,
  90,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"90","shape_dist_traveled":"","shape_pt_lat":"14.334860000000004","shape_pt_lon":"121.07716"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.332810000000004,
  121.07947,
  91,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"91","shape_dist_traveled":"","shape_pt_lat":"14.332810000000004","shape_pt_lon":"121.07947"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330890000000004,
  121.08155000000001,
  92,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"92","shape_dist_traveled":"","shape_pt_lat":"14.330890000000004","shape_pt_lon":"121.08155000000001"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330860000000003,
  121.08155000000001,
  93,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"93","shape_dist_traveled":"","shape_pt_lat":"14.330860000000003","shape_pt_lon":"121.08155000000001"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330870000000003,
  121.08153,
  94,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"94","shape_dist_traveled":"","shape_pt_lat":"14.330870000000003","shape_pt_lon":"121.08153"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330870000000003,
  121.08153,
  95,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"95","shape_dist_traveled":"","shape_pt_lat":"14.330870000000003","shape_pt_lon":"121.08153"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330870000000003,
  121.08153,
  96,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"96","shape_dist_traveled":"","shape_pt_lat":"14.330870000000003","shape_pt_lon":"121.08153"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330870000000003,
  121.08153,
  97,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"97","shape_dist_traveled":"","shape_pt_lat":"14.330870000000003","shape_pt_lon":"121.08153"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330870000000003,
  121.08153,
  98,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"98","shape_dist_traveled":"","shape_pt_lat":"14.330870000000003","shape_pt_lon":"121.08153"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_shapes (
  shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled, raw
)
values (
  '882086',
  14.330870000000003,
  121.08153,
  99,
  null,
  '{"shape_id":"882086","shape_pt_sequence":"99","shape_dist_traveled":"","shape_pt_lat":"14.330870000000003","shape_pt_lon":"121.08153"}'::jsonb
)
on conflict (shape_id, shape_pt_sequence) do update set
  shape_pt_lat = excluded.shape_pt_lat,
  shape_pt_lon = excluded.shape_pt_lon,
  shape_dist_traveled = excluded.shape_dist_traveled,
  raw = excluded.raw,
  imported_at = now();

commit;
