begin;

-- Generated by scripts/import-transit-data.mjs

-- gtfs_feed_info from feed_info.txt

insert into public.gtfs_feed_info (
  feed_publisher_name, feed_publisher_url, feed_lang, default_lang, feed_start_date, feed_end_date, feed_version, raw
)
values (
  'Sakay.ph',
  'http://sakay.ph',
  'en',
  null,
  null,
  null,
  null,
  '{"feed_publisher_name":"Sakay.ph","feed_publisher_url":"http://sakay.ph","feed_lang":"en"}'::jsonb
)
on conflict (feed_publisher_name, feed_publisher_url, feed_lang) do update set
  default_lang = excluded.default_lang,
  feed_start_date = excluded.feed_start_date,
  feed_end_date = excluded.feed_end_date,
  feed_version = excluded.feed_version,
  raw = excluded.raw,
  imported_at = now();

commit;
