begin;

-- Generated by scripts/import-transit-data.mjs

-- gtfs_frequencies from frequencies.txt

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724797',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724797","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724782',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724782","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724783',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724783","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724768',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724768","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724769',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724769","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724770',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724770","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724771',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724771","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724775',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724775","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724772',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724772","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724847',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724847","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724846',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724846","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724845',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724845","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724844',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724844","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724843',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724843","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724842',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724842","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724841',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724841","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724840',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724840","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724752',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724752","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724753',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724753","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724754',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724754","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724755',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724755","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724756',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724756","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724757',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724757","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724758',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724758","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724759',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724759","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724760',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724760","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724763',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724763","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724762',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724762","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724740',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724740","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724764',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724764","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724767',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724767","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724766',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724766","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724761',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724761","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724737',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724737","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724738',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724738","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724739',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724739","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724748',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724748","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724741',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724741","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724742',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724742","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724743',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724743","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724736',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724736","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724898',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724898","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724897',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724897","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724900',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724900","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724899',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724899","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724781',
  '07:00:00',
  '21:00:00',
  1050,
  0,
  '{"trip_id":"724781","start_time":"07:00:00","end_time":"21:00:00","headway_secs":"1050","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724896',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724896","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '881763',
  '08:00:00',
  '24:00:00',
  900,
  0,
  '{"trip_id":"881763","start_time":"08:00:00","end_time":"24:00:00","headway_secs":"900","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724903',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724903","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724904',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724904","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724901',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724901","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724902',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724902","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724907',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724907","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724908',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724908","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724905',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724905","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724906',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724906","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724911',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724911","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724913',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724913","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724909',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724909","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724910',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724910","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724914',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724914","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724917',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724917","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724912',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724912","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724915',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724915","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724921',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724921","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724918',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724918","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724919',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724919","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724916',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724916","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724925',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724925","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724922',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724922","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724923',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724923","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724920',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724920","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724866',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724866","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724926',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724926","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724927',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724927","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724924',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724924","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724870',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724870","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724865',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724865","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724864',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724864","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724867',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724867","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724871',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724871","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724868',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724868","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724869',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724869","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724874',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724874","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724875',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724875","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724872',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724872","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724873',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724873","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724878',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724878","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724879',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724879","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724876',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724876","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724877',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724877","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724883',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724883","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724882',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724882","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724881',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724881","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724880',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724880","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724887',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724887","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724885',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724885","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724886',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724886","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724891',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724891","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724884',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724884","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724889',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724889","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724890',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724890","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724895',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724895","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724888',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724888","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724893',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724893","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724894',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724894","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724964',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724964","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724892',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724892","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724966',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724966","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724965',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724965","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724960',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724960","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  '724967',
  '06:00:00',
  '23:00:00',
  60,
  0,
  '{"trip_id":"724967","start_time":"06:00:00","end_time":"23:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  'FORT_CENT_1',
  '06:00:00',
  '22:00:00',
  60,
  0,
  '{"trip_id":"FORT_CENT_1","start_time":"06:00:00","end_time":"22:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

insert into public.gtfs_frequencies (
  trip_id, start_time, end_time, headway_secs, exact_times, raw
)
values (
  'FORT_WEST_1',
  '10:00:00',
  '17:00:00',
  60,
  0,
  '{"trip_id":"FORT_WEST_1","start_time":"10:00:00","end_time":"17:00:00","headway_secs":"60","exact_times":"0"}'::jsonb
)
on conflict (trip_id, start_time, end_time) do update set
  headway_secs = excluded.headway_secs,
  exact_times = excluded.exact_times,
  raw = excluded.raw,
  imported_at = now();

commit;
